In [35]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [36]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# load books, users and rating datasets

In [37]:
datapath1 = '/content/drive/MyDrive/ml_code/nlp/book recommendation project/Books.csv'
datapath2 = '/content/drive/MyDrive/ml_code/nlp/book recommendation project/Users.csv'
datapath3 = '/content/drive/MyDrive/ml_code/nlp/book recommendation project/Ratings.csv'


books = pd.read_csv(datapath1)
users = pd.read_csv(datapath2)
ratings = pd.read_csv(datapath3)

<ipython-input-37-efe6c52f13e3>:6: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books = pd.read_csv(datapath1)

# **understanding data**

##Books dataset

In [38]:
books.head(10)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,The Mummies of Urumchi,E. J. W. Barber,1999,W. W. Norton &amp; Company,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
5,0399135782,The Kitchen God's Wife,Amy Tan,1991,Putnam Pub Group,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...,http://images.amazon.com/images/P/0399135782.0...
6,0425176428,What If?: The World's Foremost Military Histor...,Robert Cowley,2000,Berkley Publishing Group,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...,http://images.amazon.com/images/P/0425176428.0...
7,0671870432,PLEADING GUILTY,Scott Turow,1993,Audioworks,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...,http://images.amazon.com/images/P/0671870432.0...
8,0679425608,Under the Black Flag: The Romance and the Real...,David Cordingly,1996,Random House,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...,http://images.amazon.com/images/P/0679425608.0...
9,074322678X,Where You'll Find Me: And Other Stories,Ann Beattie,2002,Scribner,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...,http://images.amazon.com/images/P/074322678X.0...

In [39]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 8 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-S          271360 non-null  object
 6   Image-URL-M          271360 non-null  object
 7   Image-URL-L          271357 non-null  object
dtypes: object(8)
memory usage: 16.6+ MB

In [40]:
books.drop_duplicates(keep = "first", inplace = True)
books.reset_index(inplace = True, drop = True)

In [41]:
books.drop(columns = ["Image-URL-S", "Image-URL-M"], inplace = True)

In [42]:
books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 271360 entries, 0 to 271359
Data columns (total 6 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ISBN                 271360 non-null  object
 1   Book-Title           271360 non-null  object
 2   Book-Author          271358 non-null  object
 3   Year-Of-Publication  271360 non-null  object
 4   Publisher            271358 non-null  object
 5   Image-URL-L          271357 non-null  object
dtypes: object(6)
memory usage: 12.4+ MB

##users dataset

In [43]:
users.head(10)

   User-ID                            Location   Age
0        1                  nyc, new york, usa   NaN
1        2           stockton, california, usa  18.0
2        3     moscow, yukon territory, russia   NaN
3        4           porto, v.n.gaia, portugal  17.0
4        5  farnborough, hants, united kingdom   NaN
5        6       santa monica, california, usa  61.0
6        7                 washington, dc, usa   NaN
7        8            timmins, ontario, canada   NaN
8        9          germantown, tennessee, usa   NaN
9       10          albacete, wisconsin, spain  26.0

In [44]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

In [45]:
users.drop_duplicates(keep = "first", inplace = True)
users.reset_index(inplace = True, drop = True)

In [46]:
users.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 278858 entries, 0 to 278857
Data columns (total 3 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   User-ID   278858 non-null  int64
 1   Location  278858 non-null  object
 2   Age       168096 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.4+ MB

##ratings dataset

In [47]:
ratings.head(10)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3
4   276729  0521795028            6
5   276733  2080674722            0
6   276736  3257224281            8
7   276737  0600570967            6
8   276744  038550120X            7
9   276745   342310538           10

In [48]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

In [49]:
ratings.drop_duplicates(keep = "first", inplace = True)
ratings.reset_index(inplace = True, drop = True)

In [50]:
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 3 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
dtypes: int64(2), object(1)
memory usage: 26.3+ MB

#updating ratings df to have only those users which have given more than 50 ratings

In [51]:
num_ratings = ratings.groupby("User-ID")["Book-Rating"].count()

In [52]:
num_ratings = pd.DataFrame(num_ratings)
num_ratings.rename(columns = {"Book-Rating" : "num_rating"}, inplace=True)
num_ratings

         num_rating
User-ID
2                 1
7                 1
8                18
9                 3
10                2
...             ...
278846            2
278849            4
278851           23
278852            1
278854            8

[105283 rows x 1 columns]

In [53]:
ratings = pd.merge(ratings, num_ratings, on="User-ID")
ratings.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1149780 entries, 0 to 1149779
Data columns (total 4 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   User-ID      1149780 non-null  int64
 1   ISBN         1149780 non-null  object
 2   Book-Rating  1149780 non-null  int64
 3   num_rating   1149780 non-null  int64
dtypes: int64(3), object(1)
memory usage: 35.1+ MB

In [54]:
ratings = ratings[ratings["num_rating"] > 50]
ratings.info()

<class 'pandas.core.frame.DataFrame'>
Index: 765672 entries, 173 to 1149748
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   User-ID      765672 non-null  int64
 1   ISBN         765672 non-null  object
 2   Book-Rating  765672 non-null  int64
 3   num_rating   765672 non-null  int64
dtypes: int64(3), object(1)
memory usage: 29.2+ MB

In [55]:
ratings[ratings["User-ID"] == 183].value_counts()

User-ID  ISBN        Book-Rating  num_rating
183      058608195X  0            136           1
         9726953308  0            136           1
         9726621445  0            136           1
         9726621720  0            136           1
         9726626536  0            136           1
                                               ..
         8440630794  7            136           1
         8433920081  0            136           1
         8420639133  0            136           1
         8401422825  9            136           1
         9748440537  8            136           1
Name: count, Length: 136, dtype: int64

#Merging the ratings and books dataframes

In [56]:
# df = pd.merge(ratings, books, on="ISBN")
df = pd.merge(ratings, books, on='ISBN', how='left')

In [57]:
df.head(10)

,User-ID,ISBN,Book-Rating,num_rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,276847,0446364193,0,51,Along Came a Spider (Alex Cross Novels),James Patterson,1993,Warner Books,http://images.amazon.com/images/P/0446364193.0...
1,276847,3257200552,5,51,NaN,NaN,NaN,NaN,NaN
2,276847,3379015180,0,51,Schlafes Bruder,Robert Schneider,1994,"Reclam, Leipzig",http://images.amazon.com/images/P/3379015180.0...
3,276847,3404145909,8,51,Der Stein der Kelten.,Michael Phillips,2001,LÃ?Â¼bbe,http://images.amazon.com/images/P/3404145909.0...
4,276847,3404148576,8,51,Nordermoor,Arnaldur Indridason,2003,LÃ?Â¼bbe,http://images.amazon.com/images/P/3404148576.0...
5,276847,3404921178,7,51,Nur der Tod ist ohne Makel.,Ann Granger,2002,LÃ?Â¼bbe,http://images.amazon.com/images/P/3404921178.0...
6,276847,3423071516,10,51,Der Kleine Hobbit,J. R. R. Tolkien,2002,Distribooks,http://images.amazon.com/images/P/3423071516.0...
7,276847,3423204885,0,51,Die Benachteiligung erfolgt durch die Post. St...,Georg Friedrich Nikol,2001,Dtv,http://images.amazon.com/images/P/3423204885.0...
8,276847,3423205806,0,51,Lieber Sport als Mord.,Horst Bosetzky,2002,Dtv,http://images.amazon.com/images/P/3423205806.0...
9,276847,3426029553,8,51,NaN,NaN,NaN,NaN,NaN

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 765672 entries, 0 to 765671
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   User-ID              765672 non-null  int64
 1   ISBN                 765672 non-null  object
 2   Book-Rating          765672 non-null  int64
 3   num_rating           765672 non-null  int64
 4   Book-Title           700848 non-null  object
 5   Book-Author          700846 non-null  object
 6   Year-Of-Publication  700848 non-null  object
 7   Publisher            700846 non-null  object
 8   Image-URL-L          700845 non-null  object
dtypes: int64(3), object(6)
memory usage: 52.6+ MB

In [59]:
df.dropna(inplace = True)
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 700841 entries, 0 to 765671
Data columns (total 9 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   User-ID              700841 non-null  int64
 1   ISBN                 700841 non-null  object
 2   Book-Rating          700841 non-null  int64
 3   num_rating           700841 non-null  int64
 4   Book-Title           700841 non-null  object
 5   Book-Author          700841 non-null  object
 6   Year-Of-Publication  700841 non-null  object
 7   Publisher            700841 non-null  object
 8   Image-URL-L          700841 non-null  object
dtypes: int64(3), object(6)
memory usage: 53.5+ MB

In [60]:
df["User-ID"].value_counts()

User-ID
11676     11144
198711     6456
153662     5814
98391      5777
35859      5646
          ...
48326         4
100345        3
152464        3
76440         2
224108        1
Name: count, Length: 3370, dtype: int64

In [61]:
df[df["User-ID"] == 183]["ISBN"].value_counts()

ISBN
2070567842    1
225314696X    1
8401422825    1
8420639133    1
8433920081    1
8440630794    1
847223973X    1
8476409419    1
Name: count, dtype: int64

#Updating the df to keep only those books which have more than 100 ratings

In [62]:
df.groupby("Book-Title")["Book-Rating"].count().sort_values(ascending=False)

Book-Title
Wild Animus                                           844
The Lovely Bones: A Novel                             574
The Da Vinci Code                                     445
Bridget Jones's Diary                                 443
The Nanny Diaries: A Novel                            400
                                                     ...
Monster Goes Around the Town                            1
Monster Faces (Sesame Street - Chunky Shape Books)      1
Monster Boy (5th Grade Monsters, No 13)                 1
Monster Blood IV (Goosebumps, No 62)                    1
Prescripton Murder                                      1
Name: Book-Rating, Length: 198797, dtype: int64

In [63]:
book_rating_counts = df.groupby("Book-Title")["Book-Rating"].count()
df = df[df["Book-Title"].isin(book_rating_counts[book_rating_counts > 100].index)]
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 69927 entries, 0 to 765665
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   User-ID              69927 non-null  int64
 1   ISBN                 69927 non-null  object
 2   Book-Rating          69927 non-null  int64
 3   num_rating           69927 non-null  int64
 4   Book-Title           69927 non-null  object
 5   Book-Author          69927 non-null  object
 6   Year-Of-Publication  69927 non-null  object
 7   Publisher            69927 non-null  object
 8   Image-URL-L          69927 non-null  object
dtypes: int64(3), object(6)
memory usage: 5.3+ MB

In [64]:
aggregated_df = df.groupby(['User-ID', 'Book-Title']).agg({'Book-Rating': 'mean'}).reset_index()

In [65]:
aggregated_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68291 entries, 0 to 68290
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   User-ID      68291 non-null  int64
 1   Book-Title   68291 non-null  object
 2   Book-Rating  68291 non-null  float64
dtypes: float64(1), int64(1), object(1)
memory usage: 1.6+ MB

In [66]:
df = pd.merge(aggregated_df, df.drop(columns=['Book-Rating']), on=['User-ID', 'Book-Title'])

In [67]:
df.drop_duplicates(subset=['User-ID', 'Book-Title'], keep='first', inplace=True)

In [68]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 68291 entries, 0 to 69926
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   User-ID              68291 non-null  int64
 1   Book-Title           68291 non-null  object
 2   Book-Rating          68291 non-null  float64
 3   ISBN                 68291 non-null  object
 4   num_rating           68291 non-null  int64
 5   Book-Author          68291 non-null  object
 6   Year-Of-Publication  68291 non-null  object
 7   Publisher            68291 non-null  object
 8   Image-URL-L          68291 non-null  object
dtypes: float64(1), int64(2), object(6)
memory usage: 5.2+ MB

In [69]:
df.head(10)

,User-ID,Book-Title,Book-Rating,ISBN,num_rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-L
0,183,Fahrenheit 451,9.0,8401422825,136,Ray Bradbury,1993,"Plaza &amp; Janes Editores, S.A.",http://images.amazon.com/images/P/8401422825.0...
1,243,2nd Chance,0.0,0446612790,81,James Patterson,2003,Warner Vision,http://images.amazon.com/images/P/0446612790.0...
2,243,A Map of the World,7.0,0385720106,81,Jane Hamilton,1999,Anchor Books/Doubleday,http://images.amazon.com/images/P/0385720106.0...
3,243,A Painted House,7.0,044023722X,81,John Grisham,2001,Dell Publishing Company,http://images.amazon.com/images/P/044023722X.0...
4,243,All That Remains (Kay Scarpetta Mysteries (Pap...,0.0,0380718332,81,Patricia D. Cornwell,1993,Avon,http://images.amazon.com/images/P/0380718332.0...
5,243,Angels &amp; Demons,0.0,0743486226,81,Dan Brown,2003,Atria,http://images.amazon.com/images/P/0743486226.0...
6,243,Breathing Lessons,0.0,042511774X,81,Anne Tyler,1994,Berkley Publishing Group,http://images.amazon.com/images/P/042511774X.0...
7,243,Carolina Moon,0.0,0515130389,81,Nora Roberts,2001,Jove Books,http://images.amazon.com/images/P/0515130389.0...
8,243,Chicken Soup for the Soul (Chicken Soup for th...,5.0,155874262X,81,Jack Canfield,1993,Health Communications,http://images.amazon.com/images/P/155874262X.0...
9,243,Congo,0.0,0345378490,81,Michael Crichton,1995,Ballantine Books,http://images.amazon.com/images/P/0345378490.0...

#Creating sparse matrix of users and their ratings

In [70]:
pivot = df.pivot(index='Book-Title', columns='User-ID', values='Book-Rating')
pivot

User-ID,183,243,254,507,626,638,741,882,929,1025,...,277928,277965,278026,278137,278144,278188,278418,278582,278633,278843
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,NaN,NaN,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1st to Die: A Novel,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2nd Chance,NaN,0.0,NaN,NaN,NaN,9.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4 Blondes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
A Bend in the Road,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wild Animus,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,0.0,...,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN
Wish You Well,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Without Remorse,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Wuthering Heights,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"\O\"" Is for Outlaw""",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [71]:
pivot.fillna(value = 0, inplace = True)

In [72]:
pivot

User-ID,183,243,254,507,626,638,741,882,929,1025,...,277928,277965,278026,278137,278144,278188,278418,278582,278633,278843
Book-Title,,,,,,,,,,,,,,,,,,,,,
1984,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1st to Die: A Novel,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2nd Chance,0.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4 Blondes,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
A Bend in the Road,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Wild Animus,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Wish You Well,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Without Remorse,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Wuthering Heights,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"\O\"" Is for Outlaw""",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [73]:
from scipy.sparse import csr_matrix
matrix = csr_matrix(pivot)
matrix

<425x3117 sparse matrix of type '<class 'numpy.float64'>'
	with 21665 stored elements in Compressed Sparse Row format>

#Creating the k nearest neighbours model

In [74]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(n_neighbors= 11, algorithm="brute", metric = "cosine")
model.fit(matrix)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=11)

#get generalized book recommendations

In [75]:
def get_book_recommendations(book_title, model, pivot):
    if book_title not in pivot.index:
        return "Book title not found."

    book_index = pivot.index.get_loc(book_title)
    distances, indices = model.kneighbors(pivot.iloc[book_index, :].values.reshape(1, -1), n_neighbors=11)
    recommended_books = [pivot.index[i] for i in indices.flatten()][1:]
    return recommended_books

In [76]:
input_book = df["Book-Title"].iloc[1]
print("Recommendations for book:", input_book)
recommendation = get_book_recommendations(input_book, model, pivot)

for i in recommendation:
    print(i)

Recommendations for book: 2nd Chance
Four Blind Mice
The Beach House
Violets Are Blue
1st to Die: A Novel
Flesh and Blood
When the Wind Blows
The Next Accident
Cat &amp; Mouse (Alex Cross Novels)
The Summons
Final Target

#get personalized recommendations based on previous user ratings

In [77]:
transpose_pivot = pivot.T

In [78]:
from scipy.sparse import csr_matrix
matrix_t = csr_matrix(transpose_pivot)

In [79]:
from sklearn.neighbors import NearestNeighbors
model1 = NearestNeighbors(algorithm = "brute", metric = "cosine" ,n_neighbors = 11)
model1.fit(matrix_t)

NearestNeighbors(algorithm='brute', metric='cosine', n_neighbors=11)

In [80]:
def personalized_book_recommendations(user_id, model, pivot, df):
    if user_id not in pivot.index:
        return "User ID not found in the dataset."
    distances, indices = model.kneighbors(pivot.loc[user_id, :].values.reshape(1, -1), n_neighbors=11)
    similar_users = pivot.index[indices.flatten()][1:]

    recommended_books = set()

    for user in similar_users:
        top_books = df[df['User-ID'] == user]['Book-Title'].unique()
        recommended_books.update(top_books)

    user_rated_books = df[df['User-ID'] == user_id]['Book-Title'].unique()
    final_recommendations = list(recommended_books.difference(user_rated_books))

    return final_recommendations

In [81]:
user_inp = df["User-ID"].iloc[0]
recommendations = personalized_book_recommendations(user_inp, model1, transpose_pivot, df)

print(f"Personalized recommendations for user {user_inp}:")
for i in recommendations:
    print(i)

Personalized recommendations for user 183:
Heart of the Sea (Irish Trilogy)
Primary Colors: A Novel of Politics
The Lovely Bones: A Novel
The Return of the King (The Lord of the Rings, Part 3)
White Oleander : A Novel
Confessions of an Ugly Stepsister : A Novel
The Street Lawyer
A Map of the World
Jewels of the Sun (Irish Trilogy)
The Poisonwood Bible: A Novel
Wild Animus
Balzac and the Little Chinese Seamstress : A Novel
Dance upon the Air (Three Sisters Island Trilogy)
Heaven and Earth (Three Sisters Island Trilogy)
Angels
House of Sand and Fog
Beloved
High Fidelity
Remember Me
She's Come Undone (Oprah's Book Club)
The Deep End of the Ocean
Vinegar Hill (Oprah's Book Club (Paperback))
The Vampire Lestat (Vampire Chronicles, Book II)
The Blue Nowhere : A Novel
Dolores Claiborne
Face the Fire (Three Sisters Island Trilogy)
The Summerhouse
Back Roads
The Testament
Tears of the Moon (Irish Trilogy)
The Great Gatsby
Watchers
Watership Down
Sphere
Hannibal
F Is for Fugitive (Kinsey Millhone Mysteries (Paperback))
Wicked: The Life and Times of the Wicked Witch of the West
The Clan of the Cave Bear (Earth's Children (Paperback))
The Firm
The Notebook
The Two Towers (The Lord of the Rings, Part 2)
Heartbreaker
Summer Sisters
What Looks Like Crazy On An Ordinary Day
Along Came a Spider (Alex Cross Novels)
Harry Potter and the Prisoner of Azkaban (Book 3)
The Client
The Cardinal of the Kremlin (Jack Ryan Novels)
The Lost World
Wish You Well

#Creating models from suprise class

In [83]:
!pip install surprise

Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl.metadata (327 bytes)
Collecting scikit-surprise (from surprise)
  Downloading scikit_surprise-1.1.4.tar.gz (154 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.4/154.4 kB 2.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.4.2)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from scikit-surprise->surprise) (1.13.1)
Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (pyproject.toml) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.4-cp310-cp310-linux_x86_64.whl size=2357272 sha256=21e2920fb34fc76249eee60d4a3123d9ede033f5ea84a0e5ce8de0144f1991c0
  Stored in directory: /root/.cache/pip/wheels/4b/3f/df/6acbf0a40397d9bf3ff97f582cc22fb9ce66adde75bc71fd54
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.4 surprise-0.1

In [84]:
from surprise import Reader, Dataset
from surprise.model_selection import train_test_split, cross_validate, GridSearchCV
from surprise import KNNBasic, KNNWithMeans, KNNWithZScore, KNNBaseline, SVD
from surprise import accuracy

In [85]:
X=df.drop(columns =["num_rating"])
y=df["num_rating"]

In [86]:
reader = Reader(rating_scale=(0, 10))
data   = Dataset.load_from_df(df[['User-ID','Book-Title','Book-Rating']], reader)
raw_ratings = data.raw_ratings
import random
random.shuffle(raw_ratings)                 # shuffle dataset

threshold   = int(len(raw_ratings)*0.8)

train_raw_ratings = raw_ratings[:threshold]
test_raw_ratings  = raw_ratings[threshold:]

data.raw_ratings = train_raw_ratings        # data is now the trainset
trainset = data.build_full_trainset()
testset = data.construct_testset(test_raw_ratings)

#training all the models to se which performs best

In [87]:
models=[KNNBasic(),KNNWithMeans(),KNNWithZScore(),SVD()]
results = {}

for model in models:
    CV_scores = cross_validate(model, data, measures=["MAE","RMSE"], cv=5, n_jobs=-1)

    result = pd.DataFrame.from_dict(CV_scores).mean(axis=0)
    results[str(model).split("algorithms.")[1].split("object ")[0]] = result

In [88]:
performance_df = pd.DataFrame.from_dict(results)
print("Model Performance: \n")
performance_df.T.sort_values(by='test_rmse')

Model Performance:

                           test_mae  test_rmse  fit_time  test_time
knns.KNNWithMeans          2.797015   3.563925  2.059153   5.137275
knns.KNNWithZScore         2.781173   3.573289  1.167247   3.405109
matrix_factorization.SVD   2.921899   3.649127  0.895293   0.129018
knns.KNNBasic              3.017348   3.698590  1.322094   5.108018

#grid search for hyperparameter tuning for knn with mmeans

In [89]:
param_grid = { 'sim_options' : {'min_support': [3,5],
                                'user_based': [False, True]}
             }

gridsearchKNNWithMeans = GridSearchCV(KNNWithMeans,
                                      param_grid = param_grid,
                                      measures=['mae', 'rmse'],
                                      cv=5,
                                      n_jobs=-1)

gridsearchKNNWithMeans.fit(data)

print(f'MAE Best Parameters:  {gridsearchKNNWithMeans.best_params["mae"]}')
print(f'MAE Best Score:       {gridsearchKNNWithMeans.best_score["mae"]}\n')

print(f'RMSE Best Parameters: {gridsearchKNNWithMeans.best_params["rmse"]}')
print(f'RMSE Best Score:      {gridsearchKNNWithMeans.best_score["rmse"]}\n')
best_params_knn = gridsearchKNNWithMeans.best_params["rmse"]

MAE Best Parameters:  {'sim_options': {'min_support': 5, 'user_based': False}}
MAE Best Score:       2.769623370067532

RMSE Best Parameters: {'sim_options': {'min_support': 5, 'user_based': False}}
RMSE Best Score:      3.621850871474268

#hyperparameter tuning for svd model using gridsearch

In [90]:
param_grid = {"n_factors": range(10,100,20),
              "n_epochs" : [5, 10, 20],
              "lr_all"   : [0.002, 0.005],
              "reg_all"  : [0.2, 0.5]}

gridsearchSVD = GridSearchCV(SVD, param_grid, measures=['mae', 'rmse'], cv=5, n_jobs=-1)

gridsearchSVD.fit(data)

print(f'MAE Best Parameters:  {gridsearchSVD.best_params["mae"]}')
print(f'MAE Best Score:       {gridsearchSVD.best_score["mae"]}\n')

print(f'RMSE Best Parameters: {gridsearchSVD.best_params["rmse"]}')
print(f'RMSE Best Score:      {gridsearchSVD.best_score["rmse"]}\n')
best_params_svd = gridsearchSVD.best_params["rmse"]

MAE Best Parameters:  {'n_factors': 30, 'n_epochs': 20, 'lr_all': 0.005, 'reg_all': 0.2}
MAE Best Score:       2.8816518650016634

RMSE Best Parameters: {'n_factors': 70, 'n_epochs': 20, 'lr_all': 0.005, 'reg_all': 0.5}
RMSE Best Score:      3.4745681459920825

In [94]:
def generate_recommendationsSVD(userID, get_recommend =10):
    model = SVD(**best_params_svd)
    model.fit(trainset)
    testset = trainset.build_anti_testset()
    predictions = model.test(testset)
    predictions_df = pd.DataFrame(predictions)
    predictions_userID = predictions_df[predictions_df['uid'] == userID].sort_values(by="est", ascending = False).head(get_recommend)

    recommendations = []
    recommendations.append(list(predictions_userID['iid']))
    recommendations = recommendations[0]

    return(recommendations)

In [101]:
recom = generate_recommendationsSVD(11676)
recom

['Coraline',
 "Gerald's Game",
 'The Drawing of the Three (The Dark Tower, Book 2)',
 'Q Is for Quarry',
 'Four Past Midnight',
 'The Color Purple',
 'The Gunslinger (The Dark Tower, Book 1)',
 'The Dark Half',
 'Four Blind Mice',
 "She's Come Undone (Oprah's Book Club)"]

In [100]:
df[df['User-ID'] == 11676]['Book-Title'].value_counts()

Book-Title
1984                                                                1
The Burden of Proof                                                 1
The Crimson Petal and the White                                     1
The Color of Water: A Black Man's Tribute to His White Mother       1
The Color Purple                                                    1
                                                                   ..
Heaven and Earth (Three Sisters Island Trilogy)                     1
Heartbreaker                                                        1
Heart of the Sea (Irish Trilogy)                                    1
Harry Potter and the Sorcerer's Stone (Harry Potter (Paperback))    1
\O\" Is for Outlaw"                                                 1
Name: count, Length: 405, dtype: int64